// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactManagementDbContext))]
    partial class ContactManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ha Noi",
                            Category = "Ban be",
                            Email = "nguyenvanan@example.com",
                            FullName = "Nguyen Van An",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ho Chi Minh",
                            Category = "Nguoi than",
                            Email = "tranthibinh@example.com",
                            FullName = "Tran Thi Binh",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Đa Nang",
                            Category = "Shipper Shopee",
                            Email = "levancuong@example.com",
                            FullName = "Le Van Cuong",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hai Phong",
                            Category = "Dong nghiep",
                            Email = "phamthidung@example.com",
                            FullName = "Pham Thi Dung",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Can Tho",
                            Category = "Nguoi than",
                            Email = "hoangvanduc@example.com",
                            FullName = "Hoang Van Đuc",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Hue",
                            Email = "dothihanh@example.com",
                            FullName = "Đo Thi Hanh",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Nha Trang",
                            Email = "buivangiang@example.com",
                            FullName = "Bui Van Giang",
                            PhoneNumber = "0912345678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
